#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: lvm
      password: ubuntu
  keyboard:
    layout: de
  locale: en_US
  packages:
    - curl
    - wget
    - libnotify-bin
  snaps:
    - name: code
      classic: true
    - name: postman
      classic: false
    - name: powershell
      classic: true
    - name: pycharm-community
      classic: true
  late-commands:
    # Update packages
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get upgrade -y

    # Install Microsoft Intune Portal
    - curtin in-target --target=/target -- mkdir -p /tmp/microsoft
    - curtin in-target --target=/target -- sh -c 'cd /tmp/microsoft && curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg'
    - curtin in-target --target=/target -- install -o root -g root -m 644 /tmp/microsoft/microsoft.gpg /usr/share/keyrings/microsoft.gpg
    - curtin in-target --target=/target -- sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/microsoft-ubuntu-noble-prod.list'
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y intune-portal

    # Install MDE
    - curtin in-target --target=/target -- wget -O /tmp/microsoft/mde_installer.sh https://raw.githubusercontent.com/microsoft/mdatp-xplat/refs/heads/master/linux/installation/mde_installer.sh
    - curtin in-target --target=/target -- chmod +x /tmp/microsoft/mde_installer.sh
    - curtin in-target --target=/target -- /tmp/microsoft/mde_installer.sh --install --channel prod -y

    # Initialize MDE service
    - curtin in-target --target=/target -- systemctl daemon-reload
    - curtin in-target --target=/target -- systemctl enable mdatp
    - curtin in-target --target=/target -- systemctl start mdatp

    # Install Microsoft Edge
    - curtin in-target --target=/target -- add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
    - curtin in-target --target=/target -- apt-get update
    - curtin in-target --target=/target -- apt-get install -y microsoft-edge-stable

    # Remove bloatware
    - curtin in-target --target=/target -- apt-get purge -y libreoffice-common
    - curtin in-target --target=/target -- apt-get purge -y libreoffice*
    - curtin in-target --target=/target -- apt-get purge -y remmina*
    - curtin in-target --target=/target -- apt-get purge -y transmission*

    # Clean up
    - curtin in-target --target=/target -- apt-get autoremove -y
    - curtin in-target --target=/target -- apt-get clean
    - curtin in-target --target=/target -- rm -rf /tmp/microsoft

    # Reboot
    - curtin in-target --target=/target -- reboot
