#cloud-config
autoinstall:
  version: 1
  user-data:
    users: [""]
    disable_root: false
  ssh:
    install-server: no
  storage:
    layout:
      name: lvm
      password: ubuntu
  keyboard:
    layout: de
  locale: en_US
  packages:
    - curl
    - wget
    - zenity  # Add zenity to initial package list
  snaps:
    - name: code
    - name: postman
    - name: powershell
    - name: pycharm-community

  late-commands:
    # Create a progress script that will run at first login
    - curtin in-target --target=/target -- bash -c 'cat > /usr/local/bin/show-install-progress << "EOF"
      #!/bin/bash
      (
        echo "10" ; sleep 2
        echo "# Installing Microsoft Intune Portal..." ; sleep 2
        
        # Intune Portal Installation
        cd /tmp
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/microsoft-ubuntu-noble-prod.list
        apt-get update
        apt-get install -y intune-portal
        
        echo "40" ; sleep 2
        echo "# Installing Microsoft Defender..." ; sleep 2
        
        # MDE Installation
        wget -O mde_installer.sh https://raw.githubusercontent.com/microsoft/mdatp-xplat/master/linux/installation/mde_installer.sh
        chmod +x mde_installer.sh
        ./mde_installer.sh --install --channel prod -y
        systemctl enable mdatp
        systemctl start mdatp
        
        echo "70" ; sleep 2
        echo "# Installing Microsoft Edge..." ; sleep 2
        
        # Edge Installation
        add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
        apt-get update
        apt-get install -y microsoft-edge-stable
        
        echo "90" ; sleep 2
        echo "# Cleaning up..." ; sleep 2
        
        # Cleanup
        apt-get autoremove -y
        apt-get clean
        rm -rf /tmp/microsoft*
        
        echo "100" ; sleep 2
      ) |
      zenity --progress \
        --title="Post-Installation Setup" \
        --text="Starting setup..." \
        --percentage=0 \
        --auto-close \
        --width=400
      
      zenity --info --text="Setup complete!" --width=200
      EOF'

    # Make the progress script executable
    - curtin in-target --target=/target -- chmod +x /usr/local/bin/show-install-progress

    # Create autostart entry for the progress script
    - curtin in-target --target=/target -- mkdir -p /etc/skel/.config/autostart
    - curtin in-target --target=/target -- bash -c 'cat > /etc/skel/.config/autostart/install-progress.desktop << "EOF"
      [Desktop Entry]
      Type=Application
      Name=Installation Progress
      Exec=/usr/local/bin/show-install-progress
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
      EOF'

    # Reboot
    - curtin in-target --target=/target -- reboot
